### PR TITLE
Fix insurance description #295

### LINKED ISSUE #295: Insurance description should not be required if insurance is not required
Currently, when "Insurance Required" is off, the event won't save if the insurance description field is empty.

Or rather, it will "save" but not apply the changes.

### PR DESCRIPTION
**Pull request by jacbz**
Closes #295

### CODE REVIEW

File: legacy-app/src/app/modules/event-templates/components/event-form-dialog/event-form-dialog.component.ts [hunk 1]
```diff
@@ -55,6 +55,18 @@ export class EventFormDialogComponent {
     }
   }
 
+  async ngOnInit() {
+    this.dialogForm
+      .get('shouldBeReportedToInsurance')
+      ?.valueChanges.subscribe((shouldBeReportedToInsurance) => {
```
Comment (heddendorp) [inline legacy-app/src/app/modules/event-templates/components/event-form-dialog/event-form-dialog.component.ts:61]: Please make sure to clean up this subscription once the component is destroyed to prevent memory leaks

File: legacy-app/src/app/modules/events/pages/event-edit-page/event-edit-page.component.ts [hunk 2]
```diff
@@ -285,6 +285,21 @@ export class EventEditPageComponent implements OnInit, OnDestroy {
...
       });
+    this.coreInformationForm
+      .get('shouldBeReportedToInsurance')
+      ?.valueChanges.pipe(
+        startWith(
+          this.coreInformationForm.get('shouldBeReportedToInsurance')?.value
+        ),
+        takeUntil(this.destroyed$)
+      )
+      .subscribe((shouldBeReportedToInsurance) => {
```
Comment (heddendorp) [inline legacy-app/src/app/modules/events/pages/event-edit-page/event-edit-page.component.ts:296]: This subscription should also be cleaned up once the component is destructed

**Review by heddendorp — CHANGES_REQUESTED** [review]

**Review by heddendorp — APPROVED** [review]
Thanks for cleaning that up 👍
